### ISSUE TITLE
Unabled to download a build of the pack

### ISSUE THREAD

**Issue by P2P-Nathan** [c22mort/AP.Remote.Access#1]
Hello @c22mort ,

I was heading to add the Remote Access pack to the SCOM Community catalog and hit a snag when I was unable to download a version from https://c22mort.github.io/RemoteAccess.html

I've got a branch ready in the community catalog and I'll create the PR once things are ready to roll.

Thanks for your contributions, looking forward to getting this pack added.

![image](https://user-images.githubusercontent.com/17866458/59097932-c215b880-8916-11e9-9be7-81b6988d9bd3.png)

**Comment by c22mort** [comment]
Hi Nathan,

Sorry about that silly typo in the download link!

Updated it, and should be good to go!

Regards

Andi
